name = "my-login-worker11"
main = "index.js"
compatibility_date = "2024-08-06"

# (Optional) Uncomment to add environment variables as secrets
# [vars]
# FIREBASE_API_KEY = ""
# CAPTCHA_SECRET_KEY = ""
